version: "3.8"

services:
  backend:
    build:
      context: ./BE-SEP490-G10-SPR25
      dockerfile: Dockerfile
    ports:
      - "5220:8080"
      - "7256:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - sqlserver
    networks:
      - app-network
    restart: on-failure

  frontend:
    build:
      context: ./FE-SEP490-G10-SPR25
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend  
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5220/api            
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password12345!"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

volumes:
  sqlserver_data:
    driver: local

networks:
  app-network:
    driver: bridge
