import type { Metadata } from "next";
import "../../app/globals.css";
import Navbar from "@/components/patient/Navbar";
import { Footer } from "@/components/patient/Footer";

export const metadata: Metadata = {
  title: "Hospital appoiment",
  description: "Generated by create next app",
};

export default function PatientLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <link rel="icon" type="image/svg+xml" href="/images/logo.png" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Hospital appoiment</title> */}
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
